import './Contents.css';
import { Link } from 'react-router-dom';
import { FaHome } from "react-icons/fa";
import { useEffect, useState } from 'react';

function Videos() {
  const [videoThumbnails, setVideoThumbnails] = useState({});

  // Load thumbnails from sessionStorage (generated by Photos component)
  useEffect(() => {
    const thumbnails = {};
    const videoFiles = [
      '/start.mp4', '/left-arrow.mp4', '/right-arrow.mp4', '/high-beam-headlights.mp4',
      '/stop-light.mp4', '/degassing.mp4', '/engine-off.mp4', '/plate.mp4'
    ];

    videoFiles.forEach(videoSrc => {
      const storedThumbnail = sessionStorage.getItem(`thumbnail_${videoSrc}`);
      if (storedThumbnail) {
        thumbnails[videoSrc] = storedThumbnail;
      }
    });
    
    setVideoThumbnails(thumbnails);
  }, []);

  return (
    <div className="projectsPage">
      <div className="projectTitle">
        <Link to="/">
          <FaHome className='iconHome' />
        </Link>
        <h2 className='foto'>VIDEO</h2>
      </div>
      <div className="projectRectangles">
        <video 
          title="Accensione motore" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={videoThumbnails['/start.mp4'] || undefined}
        >
          <source src={`${process.env.PUBLIC_URL}/start.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Freccia sinistra" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={videoThumbnails['/left-arrow.mp4'] || undefined}
        >
          <source src={`${process.env.PUBLIC_URL}/left-arrow.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Freccia destra" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={videoThumbnails['/right-arrow.mp4'] || undefined}
        >
          <source src={`${process.env.PUBLIC_URL}/right-arrow.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Abbaglianti" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={videoThumbnails['/high-beam-headlights.mp4'] || undefined}
        >
          <source src={`${process.env.PUBLIC_URL}/high-beam-headlights.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Luce stop" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={videoThumbnails['/stop-light.mp4'] || undefined}
        >
          <source src={`${process.env.PUBLIC_URL}/stop-light.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Decompressione" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={videoThumbnails['/degassing.mp4'] || undefined}
        >
          <source src={`${process.env.PUBLIC_URL}/degassing.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Spegnimento motore" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={videoThumbnails['/engine-off.mp4'] || undefined}
        >
          <source src={`${process.env.PUBLIC_URL}/engine-off.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Targa" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={videoThumbnails['/plate.mp4'] || undefined}
        >
          <source src={`${process.env.PUBLIC_URL}/plate.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>
      </div>
      <br />
    </div>
  );
}

export default Videos;