import './Contents.css';
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { FaHome } from "react-icons/fa";

function Videos() {
  const [thumbnails, setThumbnails] = useState({});

  useEffect(() => {
    // Load thumbnails from sessionStorage (generated by Photos component)
    const videoFiles = [
      'start.mp4', 'left-arrow.mp4', 'right-arrow.mp4', 'high-beam-headlights.mp4',
      'stop-light.mp4', 'degassing.mp4', 'engine-off.mp4', 'plate.mp4'
    ];

    const loadedThumbnails = {};
    videoFiles.forEach(filename => {
      const thumbnail = sessionStorage.getItem(`thumbnail_/${filename}`);
      if (thumbnail) {
        loadedThumbnails[filename] = thumbnail;
      }
    });

    setThumbnails(loadedThumbnails);
  }, []);

  return (
    <div className="projectsPage">
      <div className="projectTitle">
        <Link to="/">
          <FaHome className='iconHome' />
        </Link>
        <h2 className='foto'>VIDEO</h2>
      </div>
      <div className="projectRectangles">
        <video 
          title="Video di accensione della moto" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={thumbnails['start.mp4'] || ''}
        >
          <source src={`${process.env.PUBLIC_URL}/start.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Freccia sinistra funzionante" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={thumbnails['left-arrow.mp4'] || ''}
        >
          <source src={`${process.env.PUBLIC_URL}/left-arrow.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Freccia destra funzionante" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={thumbnails['right-arrow.mp4'] || ''}
        >
          <source src={`${process.env.PUBLIC_URL}/right-arrow.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Fari abbaglianti funzionanti" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={thumbnails['high-beam-headlights.mp4'] || ''}
        >
          <source src={`${process.env.PUBLIC_URL}/high-beam-headlights.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Stop light funzionante" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={thumbnails['stop-light.mp4'] || ''}
        >
          <source src={`${process.env.PUBLIC_URL}/stop-light.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Video del degasaggio" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={thumbnails['degassing.mp4'] || ''}
        >
          <source src={`${process.env.PUBLIC_URL}/degassing.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Spegnimento motore" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={thumbnails['engine-off.mp4'] || ''}
        >
          <source src={`${process.env.PUBLIC_URL}/engine-off.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <video 
          title="Video della targa" 
          controls 
          className="rectangle" 
          preload="none"
          loading="lazy"
          muted
          playsInline
          poster={thumbnails['plate.mp4'] || ''}
        >
          <source src={`${process.env.PUBLIC_URL}/plate.mp4`} type="video/mp4" />
          Your browser does not support the video tag.
        </video>
      </div>
      <br />
    </div>
  );
}

export default Videos;